- DESCRIPTION
- NAMESPACE
- R/RSocrata.R
- R/tests/testRSocrata.R
- README.md
This brings ls.socrata back to functioning with change to data.json and also resolves an issue where read.socrata failed when a blank date was present.
> Pull request which closes #17, resolves #18, fixes #22, close #24, fix #25

- NAMESPACE
- README.md
Don't know how I missed putting ls.socrata into the exported namespace before. I think I was loading from devtools and somehow didn't get an error. Also, noticed that the dataset listing example in the readme was off.
> ls.socrata in exported namespace; dataset listing example fix

- DESCRIPTION
- R/RSocrata.R
- README.md
- RSocrata.Rproj
If accepted, this will be the build submitted to CRAN as the first stable version of 1.6.0. This stable version (cumulatively since v1.5.1) includes the following
* Adds a new function, `ls.socrata()` that allows users to download the list of datasets available on the CRAN portal
* Adds a new optional argument, `app_token`, in `read.socrata()` that allows users to supply an API token to minimize throttling.
* Repairs a bug where ```read.socrata``` failed when reading in a date with a column, but there are null values in that column.\
If accepted, this will be submitted to CRAN as version 1.6.0.
> Proposed release candidate for v1.6.0

- .travis.yml
- DESCRIPTION
Hi @tomschenkjr, 
This PR updates travis "c" to proper "r" version. In addition, it automatically fetches newest changes from github repos so that you can test against `bleeding edge version` of 4 packages.
LInk to my travis as this passes what it needs to pass:
https://travis-ci.org/dmpe/RSocrata/builds
PS: The test run 10 minutes, because of roxygen2 and its dependencies. However, on almost every ubuntu image (non-travis) it will take FAR less. 
https://travis-ci.org/Chicago/RSocrata/builds/69931842
https://travis-ci.org/dmpe/RSocrata/builds/69934202
> update travis to a new version, i.e. proper "r" instead of old "c"

- DESCRIPTION
- R/RSocrata.R
- tests/testthat/test-all.R
Fixes #68 by making `posixify` check the whole vector rather than just the first element, also using `grep` now which is more memory efficient and returns simpler results than `regexpr`.
Added and updated tests for date / times.
> Iss68, NAs in date columns

- DESCRIPTION
- NEWS.md
Some clean-up. Version number had skipped from 1.7.1-x to 1.7.2-x. I've reconciled that back to 1.7.1 (since it hasn't been submitted to CRAN). I looked at the commit history and set the version to  1.7.1-10, which reflects the number of commits between 1.7.1 and 1.7.2.
Second, I updated the `NEWS` file to reflect the bug fixes. @geneorama - let me know if I'm missing anything.
> Fixed version numbering; updated NEWS

- .travis.yml
- DESCRIPTION
- NEWS.md
Testing against the previous R version, the current R version, and will test against the most recent development version. Should help ensure see if we break anything outside of the most recent version of R.
See examples of the new build outcomes at https://travis-ci.org/Chicago/RSocrata/builds/115609806.
@geneorama - can you just do a quick review? Just want to make sure you see this before merging it into dev.
> Travis builds now testing against multiple R versions. Closes #89

- DESCRIPTION
- R/RSocrata.R
- tests/testthat/test-all.R
> Fixes #85 - posixify now works with JSON downloads

- DESCRIPTION
- R/RSocrata.R
- tests/testthat/test-all.R
> Closes #107 - Convert logical fields to character for JSON API

- DESCRIPTION
- R/RSocrata.R
- tests/testthat/test-all.R
If the user does not include an `$order=` in the URL, this will insert `$order=:id`.
There are no tests provided because this issue should only occur when the a dataset is being changed at the same time `read.socrata()` is paging.
fixes #15
> fixes #15 - provide default sort order if not supplied in URL

- DESCRIPTION
- R/RSocrata.R
- tests/testthat/test-all.R
> Fix read.socrata() when $limit is present in URL

- DESCRIPTION
- R/RSocrata.R
- tests/testthat/test-all.R
This provides a fix for #72. 
The [catalog fields](https://project-open-data.cio.gov/v1.1/schema/#Catalog) are now downloaded from Socrata's [Project Open Data Metadata](https://project-open-data.cio.gov/v1.1/schema/) file, data.json, and attaches it as an attribute to the data frame obtained from `ls.socrata()`.
Added a test to ensure that the catalog fields are present as attributes.
@geneorama - can you review this pull request and accept if everything looks good?
> Adds metadata attributes to ls.socrata(). Fixes #72

- DESCRIPTION
- R/RSocrata.R
- tests/testthat/test-all.R
- Fixes a bug (#120) that causes an error when a URL contains a query with a $select=count(x) statement
- When a $select=count(x) statement is present, no $order will be imposed
> Bug Fix for issue #120

- DESCRIPTION
- R/RSocrata.R
- tests/testthat/test-all.R
* Add ability to handle date/time formats as `YYYY-MM-DDTHH:MM:SS` -- fixes #121
* If the date/time format is not properly converted, RSocrata returns the data as `chr` strings instead of `NA`. This will let the user manually convert if necessary and will reduce the severity of errors like these in the future (there are several date formats we are not handling right now)
* A warning has been added to alert users they will not have a POSIX-formatted column.
> Fixes #121

- DESCRIPTION
- R/RSocrata.R
- tests/testthat/test-all.R
* Adds a check to see if the URL passed to `read.socrata` ends with `rows.csv` or `rows.json`. If so, will rearrange the URL to be a valid API call.
* Unit tests check for `rows.json` and `rows.csv`. _Note:_ this does not support `rows.rdf` or `rows.xml`, even though that is returned from `ls.socrata()`
> Fixes #124

- DESCRIPTION
- R/RSocrata.R
I simplified some of the paging code in addition to setting the default to 50k. 
For some reason the diff is showing that the file was replaced entirely. I cannot get the diff to show only the changed code. Lines 301-329 of the old code turns into lines 301-315 of the new code.
> Closes #129

- DESCRIPTION
- tests/testthat/test-all.R
Per #141, a unit test began to fail on converting money fields to numeric in an R data frame. The cause was a change in the API field name on Chicago's data portal as part of a larger reorganization of the data.
This fix has two parts:
* Changed the name of the column so the test would pass
* Consolidated tests regarding the `no_dinero` function, which was duplicated in two parts of the testing scripts.
I've opened the pull request directly against the `master` branch, instead of the `dev` branch. Currently, the `dev` branch contains early work for v1.8.0, so I don't want to conflate the two. Since this is a limited hot patch, I've branched from `master` and am resubmitting to that same branch.
Both AppVeyor and Travis tests have passed.
Please review and concur with the changes.
> Hot patch to fix #141

- DESCRIPTION
- R/RSocrata.R
- tests/testthat/test-all.R
Added basic support for soql $query syntax. 
Basically just moves any $query to the end of the query string, and disables adding offset, count and limit when $query is present.
> #154 add support for $query syntax

- DESCRIPTION
- tests/testthat/test-all.R
Per #158, a unit test began to fail due to a change in format of column names in a sample dataset used in testing. This fix is simply to change the column names in the test script to match the names in the incoming dataset.
I've opened the pull request directly against the master branch, instead of the dev branch. Currently, the dev branch contains early work for v1.8.0, so I don't want to conflate the two. Since this is a limited hot patch, I've branched from master and am resubmitting to that same branch.
I've modeled this pull request on #142, which dealt with a nearly identical situation.
> Hot patch to fix #158

- DESCRIPTION
- tests/testthat/test-all.R
I don’t like punting and just skipping the tests, but I don’t know where I’m going to find that special dataset that is not updated, doesn’t risk changing order, and has only NULL values for the first 1,000 rows for at least one field. 
And for the second test, I don’t even know what it was testing. It’s also hard to reconstruct without any example. It looks a little familiar and I think we may have developed the example together. I don’t recall though.
The new pull request passes CRAN tests documented in #205
> skipping tests causing cran error, see comments in #205
